### ISSUE TITLE
搬瓦工CentOS 7提示system not support

### ISSUE THREAD

**Issue by MJCCode** [nanqinlang-script/testrace#1]
RT
#======================================
# Project: testrace
# Version: 1.0
# Author: nanqinlang
# Blog:   https://www.nanqinlang.com
# Github: https://github.com/nanqinlang
#======================================
[Error] system not support!
就完了

**Comment by nanqinlang** [comment]
你这是用到了已经被废弃的旧版本的脚本了。

用现在的 readme 里的链接就是最新的。
